title: Hedreon's Webiste

author:
  name: Made by Hedreon, for Hedreon.

description: >
  An epic blog thing that's probably temporary or is only used for one thing
  and/or another.

header_pages:
  - /mmddchangelog/

plugins:
  - jekyll-feed
  - jekyll-remote-theme
remote_theme: jekyll/minima

minima:
  skin: dark