title: Hedreon's Webiste

author:
  name: Made by Hedreon, for Hedreon.

description: >
  An epic thing that's only used for one thing and/or another.

header_pages:
  - /changelogs/index.md

plugins:
  - jekyll-remote-theme
remote_theme: jekyll/minima

minima:
  skin: dark